# Uncomment the next line to define a global platform for your project
platform :ios, '14.0'

use_frameworks!

install! 'cocoapods',
            :warn_for_unused_master_specs_repo => false

target 'Task1' do
  pod 'SwiftLint'

end
